<?php
return array (
  20 => 
  array (
    'id' => '20',
    'catid' => '13',
    'typeid' => '0',
    'title' => '爱惠家爱回家',
    'style' => '',
    'thumb' => 'http://www.aihj.ren/uploadfile/2016/1219/20161219101331702.png',
    'keywords' => '爱惠',
    'description' => '爱惠家爱惠家',
    'posids' => '1',
    'url' => 'http://www.aihj.ren/index.php?m=content&c=index&a=show&catid=13&id=20',
    'listorder' => '1',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'aihj',
    'inputtime' => '1482113585',
    'updatetime' => '1482139262',
    'hitsid' => 'c-1-20',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '13',
    'typeid' => '0',
    'title' => '爱惠家爱回家',
    'style' => '',
    'thumb' => 'http://www.aihj.ren/uploadfile/2016/1219/20161219042919585.png',
    'keywords' => '爱惠',
    'description' => '北京爱惠家网络有限公司',
    'posids' => '1',
    'url' => 'http://www.aihj.ren/index.php?m=content&c=index&a=show&catid=13&id=13',
    'listorder' => '8',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'aihj',
    'inputtime' => '1482051554',
    'updatetime' => '1482051590',
    'hitsid' => 'c-1-13',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '13',
    'typeid' => '0',
    'title' => '爱惠家爱惠家',
    'style' => '',
    'thumb' => 'http://www.aihj.ren/uploadfile/2016/1219/20161219042859122.png',
    'keywords' => '爱惠',
    'description' => '北京爱惠家网络有限公司',
    'posids' => '1',
    'url' => 'http://www.aihj.ren/index.php?m=content&c=index&a=show&catid=13&id=14',
    'listorder' => '7',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'aihj',
    'inputtime' => '1482051594',
    'updatetime' => '1482051623',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '13',
    'typeid' => '0',
    'title' => '爱惠家爱回家',
    'style' => '',
    'thumb' => 'http://www.aihj.ren/uploadfile/2016/1219/20161219042840887.png',
    'keywords' => '爱惠',
    'description' => '北京爱惠家网络有限公司',
    'posids' => '1',
    'url' => 'http://www.aihj.ren/index.php?m=content&c=index&a=show&catid=13&id=15',
    'listorder' => '6',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'aihj',
    'inputtime' => '1482051626',
    'updatetime' => '1482051662',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '13',
    'typeid' => '0',
    'title' => '爱惠家爱回家',
    'style' => '',
    'thumb' => 'http://www.aihj.ren/uploadfile/2016/1219/20161219042817263.png',
    'keywords' => '爱惠',
    'description' => '北京爱惠家网络有限公司',
    'posids' => '1',
    'url' => 'http://www.aihj.ren/index.php?m=content&c=index&a=show&catid=13&id=16',
    'listorder' => '5',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'aihj',
    'inputtime' => '1482110674',
    'updatetime' => '1482110703',
    'hitsid' => 'c-1-16',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '13',
    'typeid' => '0',
    'title' => '爱惠家爱回家',
    'style' => '',
    'thumb' => 'http://www.aihj.ren/uploadfile/2016/1219/20161219042750666.png',
    'keywords' => '爱惠',
    'description' => '北京爱惠家网络有限公司',
    'posids' => '1',
    'url' => 'http://www.aihj.ren/index.php?m=content&c=index&a=show&catid=13&id=17',
    'listorder' => '4',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'aihj',
    'inputtime' => '1482110707',
    'updatetime' => '1482110737',
    'hitsid' => 'c-1-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '13',
    'typeid' => '0',
    'title' => '爱惠家爱回家',
    'style' => '',
    'thumb' => 'http://www.aihj.ren/uploadfile/2016/1219/20161219042721126.png',
    'keywords' => '爱惠',
    'description' => '北京爱惠家网络有限公司',
    'posids' => '1',
    'url' => 'http://www.aihj.ren/index.php?m=content&c=index&a=show&catid=13&id=18',
    'listorder' => '3',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'aihj',
    'inputtime' => '1482110740',
    'updatetime' => '1482110769',
    'hitsid' => 'c-1-18',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  19 => 
  array (
    'id' => '19',
    'catid' => '13',
    'typeid' => '0',
    'title' => '爱惠家公司介绍',
    'style' => '',
    'thumb' => 'http://localhost/uploadfile/2017/0111/20170111115043762.jpg',
    'keywords' => '爱惠家,来福,爱惠家爱回家',
    'description' => '北京爱惠家网络有限公司以关爱父母为主旨；以提升父母生活品质，让父母生活的更快乐的服务为己任，为他们提供便利迅捷的服务。',
    'posids' => '1',
    'url' => 'http://www.aihj.ren/index.php?m=content&c=index&a=show&catid=13&id=19',
    'listorder' => '2',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'aihj',
    'inputtime' => '1482112771',
    'updatetime' => '1482112895',
    'hitsid' => 'c-1-19',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>